import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import com.google.gson.Gson;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;
import com.mongodb.MongoCredential;
import com.mongodb.ServerAddress;
import com.mongodb.util.JSON;
 
 
public class Main {
	public final static String SEPARADOR = " 110011 ";
	public static void main(String[] args) throws SQLException, IOException {		
		List<String> urls = new ArrayList<String>();
		List<Documento> documentos = new ArrayList<Documento>();
		urls = getUrls();
		Gson gson = new Gson();
		Mongo mongoClient = new Mongo("localhost", 27017);  
		DB db = mongoClient.getDB("TouchFinder"); 
		DBCollection collection = db.getCollection("Documentos"); 
		int count = 1;
		for (String url : urls) {
			System.out.println(count+" de "+urls.size()+") Procesando: "+url);
			Documento doc = new Documento();
			doc = processPage(url);
			DBObject dbObject = (DBObject)JSON.parse(gson.toJson(doc));
			collection.insert(dbObject);
			count++;
		}
	}
 
	public static Documento processPage(String URL) throws SQLException, IOException{
			Documento docu = new Documento();
			Document doc = Jsoup.connect(URL).get();
			docu.setLink(URL);
			// Obtiene comentarios
			Elements questions = doc.select("a[href]");
			Elements tablasComponentes = doc.select("div#specs-list");
			
			for(Element link: tablasComponentes){
				for (Element tabla : link.select("table")) {
					
					List<Element> th = tabla.select("th");
					List<Element> tipos = tabla.select("td.ttl");
					List<Element> dato = tabla.select("td.nfo");
					
					for (int i=0; i <  tipos.size(); i++) {
						
						if(tipos.get(i).html().contains("2G bands") || tipos.get(i).html().contains("3G bands") || tipos.get(i).html().contains("4G bands")){
							docu.setNetwork(docu.getNetwork()+" "+dato.get(i).text());
						}
						if(tipos.get(i).html().contains("Primary") || tipos.get(i).html().contains("Secondary")){
							if(tipos.get(i).html().contains("Primary"))docu.setCamaraPrimaria(dato.get(i).text());
							if(tipos.get(i).html().contains("Secondary"))docu.setCamaraSecundaria(dato.get(i).text());
						}
						if(tipos.get(i).html().contains("OS") || tipos.get(i).html().contains("CPU") || tipos.get(i).html().contains("GPU") || tipos.get(i).html().contains("Chipset")){
							if(tipos.get(i).html().contains("OS"))docu.setSo(dato.get(i).text());
							if(tipos.get(i).html().contains("Chipset"))docu.setProcesador(dato.get(i).text());
							if(tipos.get(i).html().contains("CPU"))docu.setProcesador(docu.getProcesador() +" "+dato.get(i).text());
							if(tipos.get(i).html().contains("GPU"))docu.setGpu(dato.get(i).text());
						}
						if(tipos.get(i).html().contains("Size") || tipos.get(i).html().contains("Resolution")){
							docu.setDisplay(docu.getDisplay()+" "+dato.get(i).text());
						}
						if(tipos.get(i).html().contains("Card slot") || tipos.get(i).html().contains("Internal")){
							if(tipos.get(i).html().contains("Card slot")) docu.setSd(dato.get(i).text());
							if(tipos.get(i).html().contains("Internal")) docu.setMemoriaInterna(dato.get(i).text());
							if(docu.getMemoriaInterna().split(",").length > 1) docu.setRam(docu.getMemoriaInterna().split(",")[1]);
							
						}		
						if(tipos.get(i).text().length()==1 && th.size() == 1 && th.get(0).text().contains("Battery")){
							docu.setBateria(dato.get(i).text());
						}
						if(tipos.get(i).html().contains("Announced")){
							if(dato.get(i).text().split(",").length > 0) docu.setAnnio(dato.get(i).text().split(",")[0]);
							else docu.setAnnio(dato.get(i).text());
						}
					}
				}
			}
			for(Element link: questions){
				if(link.text().contains("Read opinions")){
					docu.setComentarios(procesaComentarios(link.attr("abs:href")));;
				}		
			}
			
			Elements modelo = doc.select("h1.section");
			Elements popularidad = doc.select("li#popularity-vote").select("strong");
			Elements diseno = doc.select("li#design-vote").select("strong");
			Elements caracteristicas = doc.select("li#features-vote").select("strong");
			Elements performance = doc.select("li#performance-vote").select("strong");
			
			if(modelo.size() > 0 && modelo.get(0).text().split(" ").length > 0){
				docu.setMarca(modelo.get(0).text().split(" ")[0]);
				docu.setModelo(modelo.get(0).text().replace(modelo.get(0).text().split(" ")[0], ""));
			}
			if(popularidad.size() == 1)
				docu.setPopularidad(popularidad.get(0).text());
			
			if(diseno.size() == 1)
				docu.setDiseno(diseno.get(0).text());
				
			if(caracteristicas.size() == 1)
				docu.setCaracteristica(caracteristicas.get(0).text());
	
			if(performance.size() == 1)
				docu.setRendimiento(performance.get(0).text());
			
			return docu;
	}
	
	public static String procesaComentarios(String URL){
		Document doc;
		String comentarios="";
		int contadorComentarios = 0;
		String URLFinal = URL;
		try {
			for(int i=1; i < 6; i++){
				if(i != 1)URLFinal = URL.substring(0, URL.length()-4)+"p"+i+".php";
				doc = Jsoup.connect(URLFinal).get();
				Elements questions = doc.select("div.user-thread");
				for(Element link: questions){
					for (Element element : link.select("p.uopin")) {
						contadorComentarios++;
						if(contadorComentarios == 1)comentarios = element.html().replace(element.select("a").toString(), "").replace("<br />", "") + SEPARADOR;
						else comentarios = comentarios + element.html().replace(element.select("a").toString(), "").replace("<br />", "") + SEPARADOR;
					}
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		//System.out.println(comentarios);
		return comentarios;
	}
	
	private static List<String> getUrls(){
		List<String> urls = new ArrayList<String>();
		urls.add("http://www.gsmarena.com/samsung_galaxy_tab_3_v-7134.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_tab_a_9_7-7122.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_tab_a_8_0-7121.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_xcover_3-6990.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s6_edge_%28cdma%29-7166.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s6_%28cdma%29-7164.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s6_edge-7079.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s6-6849.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_j1_4g-7034.php");
		urls.add("http://www.gsmarena.com/samsung_z1-6894.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a7_duos-7132.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a7-6763.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_grand_max-6905.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_e7-6879.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_e5-6906.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_core_prime-6716.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a5_duos-6802.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a5-6761.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a3_duos-6803.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_a3-6762.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s5_plus-6748.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_v-6725.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_grand_prime-6708.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_ace_style_lte-6706.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_note_edge-6631.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_note_4-6434.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_tab_active-6659.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_mega_2-6482.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_alpha-6573.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s5_mini_duos-6563.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_avant-6542.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s5_mini-6252.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_ace_4-6479.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_young_2-6480.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_core_ii-6331.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_tab_s_8_4-6439.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_core_lite_lte-6432.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_w-6404.php");
		urls.add("http://www.gsmarena.com/samsung_z-6403.php");
		urls.add("http://www.gsmarena.com/samsung_ativ_se-6245.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s5-6033.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_grand_neo-5958.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_j-5887.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_grand_2-5862.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_express_2-5803.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_light-5786.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_ace_3-5479.php");
		urls.add("http://www.gsmarena.com/samsung_i9300_galaxy_s_iii-4238.php");
		urls.add("http://www.gsmarena.com/samsung_galaxy_s_iii_i747-4803.php");
		urls.add("http://www.gsmarena.com/samsung_focus_2_i667-4745.php");
		
		urls.add("http://www.gsmarena.com/apple_iphone_6_plus-6665.php");
		urls.add("http://www.gsmarena.com/apple_iphone_6-6378.php");
		urls.add("http://www.gsmarena.com/apple_iphone_5s-5685.php");
		urls.add("http://www.gsmarena.com/apple_iphone_5c-5690.php");
		urls.add("http://www.gsmarena.com/apple_iphone_5-4910.php");
		urls.add("http://www.gsmarena.com/apple_iphone_4s-4212.php");
		urls.add("http://www.gsmarena.com/apple_iphone_4-3275.php");
		urls.add("http://www.gsmarena.com/apple_iphone_4_cdma-3716.php");
		urls.add("http://www.gsmarena.com/apple_iphone_3gs-2826.php");
		urls.add("http://www.gsmarena.com/apple_iphone_3g-2424.php");
		urls.add("http://www.gsmarena.com/apple_iphone-1827.php");
		
		urls.add("http://www.gsmarena.com/nokia_lumia_730_dual_sim-6640.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_520-5322.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_630-6232.php");
		urls.add("http://www.gsmarena.com/nokia_xl-6148.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_830-6638.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_635-6254.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_1020-5506.php");
		urls.add("http://www.gsmarena.com/nokia_x-6067.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_735-6639.php");
		urls.add("http://www.gsmarena.com/nokia_x2_dual_sim-6383.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_530-6523.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_720-5321.php");
		urls.add("http://www.gsmarena.com/nokia_n8-3252.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_610-4576.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_820-4968.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_800-4240.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_710-4276.php");
		urls.add("http://www.gsmarena.com/nokia_asha_501-5445.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_630_dual_sim-6255.php");
		urls.add("http://www.gsmarena.com/nokia_n9-3398.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_900-4578.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_icon-5833.php");
		urls.add("http://www.gsmarena.com/nokia_5233-3390.php");
		urls.add("http://www.gsmarena.com/nokia_5800_xpressmusic-2537.php");
		urls.add("http://www.gsmarena.com/nokia_808_pureview-4577.php");
		urls.add("http://www.gsmarena.com/nokia_c5_03-3578.php");
		urls.add("http://www.gsmarena.com/nokia_e7-3545.php");
		urls.add("http://www.gsmarena.com/nokia_c7-3394.php");
		urls.add("http://www.gsmarena.com/nokia_asha_503-5794.php");
		urls.add("http://www.gsmarena.com/nokia_500-4085.php");
		urls.add("http://www.gsmarena.com/nokia_x+-6147.php");
		urls.add("http://www.gsmarena.com/nokia_e6-3717.php");
		urls.add("http://www.gsmarena.com/nokia_asha_230-6149.php");
		urls.add("http://www.gsmarena.com/nokia_asha_502_dual_sim-5795.php");
		urls.add("http://www.gsmarena.com/nokia_x6-2922.php");
		urls.add("http://www.gsmarena.com/nokia_n97-2615.php");
		urls.add("http://www.gsmarena.com/nokia_5230-2909.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_822-5090.php");
		urls.add("http://www.gsmarena.com/nokia_c6_01-3524.php");
		urls.add("http://www.gsmarena.com/nokia_x7_00-3664.php");
		urls.add("http://www.gsmarena.com/nokia_700-4021.php");
		urls.add("http://www.gsmarena.com/nokia_701-4119.php");
		urls.add("http://www.gsmarena.com/nokia_n97_mini-2921.php");
		urls.add("http://www.gsmarena.com/nokia_603-4243.php");
		urls.add("http://www.gsmarena.com/nokia_c5_05-4223.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_505-5150.php");
		urls.add("http://www.gsmarena.com/nokia_c5_06-4220.php");
		urls.add("http://www.gsmarena.com/nokia_5235_comes_with_music-3056.php");
		urls.add("http://www.gsmarena.com/nokia_c7_astound-3885.php");
		urls.add("http://www.gsmarena.com/nokia_5800_navigation_edition-2906.php");
		urls.add("http://www.gsmarena.com/vertu_constellation-4263.php");
		urls.add("http://www.gsmarena.com/nokia_703-4133.php");
		urls.add("http://www.gsmarena.com/nokia_800c-4662.php");
		urls.add("http://www.gsmarena.com/nokia_lumia_710_t_mobile-4372.php");
		urls.add("http://www.gsmarena.com/nokia_c5_04-4222.php");
		
		urls.add("http://www.gsmarena.com/lg_aka-7148.php");
		urls.add("http://www.gsmarena.com/lg_magna-7051.php");
		urls.add("http://www.gsmarena.com/lg_spirit-7052.php");
		urls.add("http://www.gsmarena.com/lg_leon-7053.php");
		urls.add("http://www.gsmarena.com/lg_joy-7054.php");
		urls.add("http://www.gsmarena.com/lg_g_flex2-6916.php");
		urls.add("http://www.gsmarena.com/lg_tribute-6812.php");
		urls.add("http://www.gsmarena.com/lg_l_prime-6775.php");
		urls.add("http://www.gsmarena.com/lg_g2_lite-6776.php");
		urls.add("http://www.gsmarena.com/lg_g3_dual_lte-6764.php");
		urls.add("http://www.gsmarena.com/lg_g3_screen-6750.php");
		urls.add("http://www.gsmarena.com/lg_f60-6709.php");
		urls.add("http://www.gsmarena.com/lg_l60-6606.php");
		urls.add("http://www.gsmarena.com/lg_l60_dual-6415.php");
		urls.add("http://www.gsmarena.com/lg_g3_stylus-6555.php");
		urls.add("http://www.gsmarena.com/lg_l_bello-6593.php");
		urls.add("http://www.gsmarena.com/lg_l_fino-6592.php");
		urls.add("http://www.gsmarena.com/lg_g_pad_8_0_lte-6575.php");
		urls.add("http://www.gsmarena.com/lg_g_vista-6569.php");
		urls.add("http://www.gsmarena.com/lg_g3_a-6562.php");
		urls.add("http://www.gsmarena.com/lg_l50-6546.php");
		urls.add("http://www.gsmarena.com/lg_l30-6547.php");
		urls.add("http://www.gsmarena.com/lg_l20-6548.php");
		urls.add("http://www.gsmarena.com/lg_g3_s-6475.php");
		urls.add("http://www.gsmarena.com/lg_l65_d280-6315.php");
		urls.add("http://www.gsmarena.com/lg_g3-6294.php");
		urls.add("http://www.gsmarena.com/lg_l35-6366.php");
		urls.add("http://www.gsmarena.com/lg_volt-6357.php");
		urls.add("http://www.gsmarena.com/lg_l80_dual-6333.php");
		urls.add("http://www.gsmarena.com/lg_lucid_3_vs876-6326.php");
		urls.add("http://www.gsmarena.com/lg_l65_dual_d285-6307.php");
		urls.add("http://www.gsmarena.com/lg_f70_d315-6133.php");
		urls.add("http://www.gsmarena.com/lg_g2_mini-6077.php");
		urls.add("http://www.gsmarena.com/lg_l90_d405-6100.php");
		urls.add("http://www.gsmarena.com/lg_l70_d320n-6285.php");
		urls.add("http://www.gsmarena.com/lg_l40_d160-6286.php");
		urls.add("http://www.gsmarena.com/lg_g_pro_2-6052.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l1_ii_tri_e475-6032.php");
		urls.add("http://www.gsmarena.com/lg_gx_f310l-5901.php");
		urls.add("http://www.gsmarena.com/lg_nexus_5-5705.php");
		urls.add("http://www.gsmarena.com/lg_g_flex-5806.php");
		urls.add("http://www.gsmarena.com/lg_g_pro_lite-5772.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l2_ii_e435-5750.php");
		urls.add("http://www.gsmarena.com/lg_g2-5543.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l9_ii-5650.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l4_ii_e440-5487.php");
		urls.add("http://www.gsmarena.com/lg_optimus_f3-5509.php");
		urls.add("http://www.gsmarena.com/lg_lucid2_vs870-5390.php");
		urls.add("http://www.gsmarena.com/lg_optimus_f7-5315.php");
		urls.add("http://www.gsmarena.com/lg_optimus_f6-5722.php");
		urls.add("http://www.gsmarena.com/lg_optimus_f5-5316.php");
		urls.add("http://www.gsmarena.com/lg_optimus_g_pro_e985-5254.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l7_ii_dual_p715-5372.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l7_ii_p710-5275.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l5_ii_dual_e455-5373.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l5_ii_e460-5293.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l3_ii_dual_e435-5389.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l3_ii_e430-5292.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l1_ii_e410-5608.php");
		urls.add("http://www.gsmarena.com/lg_nexus_4_e960-5048.php");
		urls.add("http://www.gsmarena.com/lg_spectrum_ii_4g_vs930-5078.php");
		urls.add("http://www.gsmarena.com/lg_mach_ls860-5032.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l9_p769-5025.php");
		urls.add("http://www.gsmarena.com/lg_optimus_vu_ii-5325.php");
		urls.add("http://www.gsmarena.com/lg_optimus_vu_ii_f200-4950.php");
		urls.add("http://www.gsmarena.com/lg_optimus_g_e970-5062.php");
		urls.add("http://www.gsmarena.com/lg_optimus_g_ls970-4751.php");
		urls.add("http://www.gsmarena.com/lg_optimus_g_e975-4941.php");
		urls.add("http://www.gsmarena.com/lg_intuition_vs950-5005.php");
		urls.add("http://www.gsmarena.com/lg_splendor_us730-4982.php");
		urls.add("http://www.gsmarena.com/lg_escape_p870-4981.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l5_dual_e615-4964.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l9_p760-4955.php");
		urls.add("http://www.gsmarena.com/lg_motion_4g_ms770-4948.php");
		urls.add("http://www.gsmarena.com/lg_optimus_vu_p895-4932.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l3_e405-4835.php");
		urls.add("http://www.gsmarena.com/lg_optimus_elite_ls696-4749.php");
		urls.add("http://www.gsmarena.com/lg_optimus_lte2-4739.php");
		urls.add("http://www.gsmarena.com/lg_optimus_true_hd_lte_p936-4717.php");
		urls.add("http://www.gsmarena.com/lg_lucid_4g_vs840-4653.php");
		urls.add("http://www.gsmarena.com/lg_optimus_m+_ms695-4649.php");
		urls.add("http://www.gsmarena.com/lg_optimus_4x_hd_p880-4563.php");
		urls.add("http://www.gsmarena.com/lg_optimus_3d_max_p720-4562.php");
		urls.add("http://www.gsmarena.com/lg_optimus_3d_cube_su870-4545.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l7_p700-4565.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l5_e610-4571.php");
		urls.add("http://www.gsmarena.com/lg_optimus_vu_f100s-4554.php");
		urls.add("http://www.gsmarena.com/lg_optimus_lte_tag-4555.php");
		urls.add("http://www.gsmarena.com/lg_optimus_l3_e400-4461.php");
		urls.add("http://www.gsmarena.com/lg_connect_4g_ms840-4430.php");
		urls.add("http://www.gsmarena.com/lg_viper_4g_lte_ls840-4416.php");
		urls.add("http://www.gsmarena.com/lg_spectrum_vs920-4377.php");
		urls.add("http://www.gsmarena.com/lg_prada_3_0-4064.php");
		urls.add("http://www.gsmarena.com/lg_nitro_hd-4329.php");
		urls.add("http://www.gsmarena.com/lg_optimus_4g_lte_p935-4353.php");
		urls.add("http://www.gsmarena.com/lg_optimus_2_as680-4402.php");
		urls.add("http://www.gsmarena.com/lg_doubleplay-4257.php");
		urls.add("http://www.gsmarena.com/lg_enlighten_vs700-4352.php");
		urls.add("http://www.gsmarena.com/lg_jil_sander_mobile-4221.php");
		urls.add("http://www.gsmarena.com/lg_optimus_slider-4286.php");
		urls.add("http://www.gsmarena.com/lg_optimus_lte_su640-4213.php");
		urls.add("http://www.gsmarena.com/lg_optimus_lte_lu6200-4188.php");
		urls.add("http://www.gsmarena.com/lg_optimus_ex_su880-4201.php");
		urls.add("http://www.gsmarena.com/lg_optimus_q2_lu6500-4140.php");
		urls.add("http://www.gsmarena.com/lg_optimus_hub_e510-4157.php");
		urls.add("http://www.gsmarena.com/lg_optimus_sol_e730-4067.php");
		urls.add("http://www.gsmarena.com/lg_optimus_net_dual-4309.php");
		urls.add("http://www.gsmarena.com/lg_optimus_net-4043.php");
		urls.add("http://www.gsmarena.com/lg_esteem_ms910-4289.php");
		urls.add("http://www.gsmarena.com/lg_marquee_ls855-4287.php");
		urls.add("http://www.gsmarena.com/lg_optimus_black_%28white_version%29-4037.php");
		urls.add("http://www.gsmarena.com/lg_optimus_pro_c660-4040.php");
		urls.add("http://www.gsmarena.com/lg_optimus_big_lu6800-3937.php");
		urls.add("http://www.gsmarena.com/lg_us760_genesis-4033.php");
		urls.add("http://www.gsmarena.com/lg_phoenix_p505-3924.php");
		urls.add("http://www.gsmarena.com/lg_thrive_p506-3918.php");
		urls.add("http://www.gsmarena.com/lg_thrill_4g_p925-3886.php");
		urls.add("http://www.gsmarena.com/lg_optimus_3d_p920-3759.php");
		urls.add("http://www.gsmarena.com/lg_optimus_chat_c550-3837.php");
		urls.add("http://www.gsmarena.com/lg_optimus_me_p350-3735.php");
		urls.add("http://www.gsmarena.com/lg_optimus_black_p970-3704.php");
		urls.add("http://www.gsmarena.com/lg_optimus_2x_su660-3762.php");
		urls.add("http://www.gsmarena.com/lg_optimus_2x-3598.php");
		urls.add("http://www.gsmarena.com/lg_optimus_mach_lu3000-3667.php");
		urls.add("http://www.gsmarena.com/lg_revolution-3732.php");
		urls.add("http://www.gsmarena.com/lg_axis-3731.php");
		urls.add("http://www.gsmarena.com/lg_apex-3632.php");
		urls.add("http://www.gsmarena.com/lg_vortex_vs660-3630.php");
		urls.add("http://www.gsmarena.com/lg_quantum-3558.php");
		urls.add("http://www.gsmarena.com/lg_c900_optimus_7q_-3555.php");
		urls.add("http://www.gsmarena.com/lg_e900_optimus_7-3532.php");
		urls.add("http://www.gsmarena.com/lg_optimus_chic_e720-3494.php");
		urls.add("http://www.gsmarena.com/lg_optimus_m-3669.php");
		urls.add("http://www.gsmarena.com/lg_optimus_s-3583.php");
		urls.add("http://www.gsmarena.com/lg_optimus_t-3544.php");
		urls.add("http://www.gsmarena.com/lg_optimus_one_p500-3516.php");
		
		urls.add("http://www.gsmarena.com/sony_xperia_m4_aqua_dual-7100.php");
		urls.add("http://www.gsmarena.com/sony_xperia_m4_aqua-7068.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4g-7059.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4g_dual-7060.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4g_dual-7060.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4g_dual-7060.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4_dual-7031.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e4-6882.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e3_dual-6663.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e3-6634.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z3_dual-6632.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z3v-6796.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z3-6539.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z3_compact-6538.php");
		urls.add("http://www.gsmarena.com/sony_xperia_m2_aqua-6582.php");
		urls.add("http://www.gsmarena.com/sony_xperia_c3_dual-6489.php");
		urls.add("http://www.gsmarena.com/sony_xperia_c3-6488.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z2a-6456.php");
		urls.add("http://www.gsmarena.com/sony_xperia_t3-6408.php");
		urls.add("http://www.gsmarena.com/sony_xperia_m2-6146.php");
		urls.add("http://www.gsmarena.com/sony_xperia_m2_dual-6162.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z2-6144.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e1_dual-5967.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e1-5966.php");
		urls.add("http://www.gsmarena.com/sony_xperia_t2_ultra_dual-5968.php");
		urls.add("http://www.gsmarena.com/sony_xperia_t2_ultra-5965.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z1s-5950.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z1_compact-5753.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z1-5596.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z_ultra-5540.php");
		urls.add("http://www.gsmarena.com/sony_xperia_c-5541.php");
		urls.add("http://www.gsmarena.com/sony_xperia_m-5497.php");
		urls.add("http://www.gsmarena.com/sony_xperia_zr-5421.php");
		urls.add("http://www.gsmarena.com/sony_xperia_l-5363.php");
		urls.add("http://www.gsmarena.com/sony_xperia_sp-5364.php");
		urls.add("http://www.gsmarena.com/sony_xperia_z-5204.php");
		urls.add("http://www.gsmarena.com/sony_xperia_zl-5203.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e_dual-5148.php");
		urls.add("http://www.gsmarena.com/sony_xperia_e-5149.php");
		urls.add("http://www.gsmarena.com/sony_xperia_t_lte-5015.php");
		urls.add("http://www.gsmarena.com/sony_xperia_v-4958.php");
		urls.add("http://www.gsmarena.com/sony_xperia_j-4930.php");
		urls.add("http://www.gsmarena.com/sony_xperia_tx-4959.php");
		urls.add("http://www.gsmarena.com/sony_xperia_sl-4894.php");
		urls.add("http://www.gsmarena.com/sony_xperia_tipo-4718.php");
		urls.add("http://www.gsmarena.com/sony_xperia_go-4782.php");
		
		urls.add("http://www.gsmarena.com/htc_one_m9-6891.php");
		urls.add("http://www.gsmarena.com/htc_one_m9+-6977.php");
		urls.add("http://www.gsmarena.com/htc_desire_820-6636.php");
		urls.add("http://www.gsmarena.com/htc_one_%28m8%29-6074.php");
		urls.add("http://www.gsmarena.com/htc_desire_826_dual_sim-6921.php");
		urls.add("http://www.gsmarena.com/htc_desire_816-6073.php");
		urls.add("http://www.gsmarena.com/htc_desire_620g_dual_sim-6841.php");
		urls.add("http://www.gsmarena.com/htc_desire_816g_dual_sim-6736.php");
		urls.add("http://www.gsmarena.com/htc_desire_626g+-7183.php");
		urls.add("http://www.gsmarena.com/htc_desire_eye-6715.php");
		urls.add("http://www.gsmarena.com/htc_desire_616_dual_sim-6234.php");
		urls.add("http://www.gsmarena.com/htc_one_m8s-7165.php");
		urls.add("http://www.gsmarena.com/htc_one_e9+-7111.php");
		urls.add("http://www.gsmarena.com/htc_desire_510-6608.php");
		urls.add("http://www.gsmarena.com/htc_desire_820s_dual_sim-7115.php");
		urls.add("http://www.gsmarena.com/htc_one_%28e8%29-6397.php");
		urls.add("http://www.gsmarena.com/htc_desire_516_dual_sim-6463.php");
		urls.add("http://www.gsmarena.com/htc_one_x-4320.php");
		urls.add("http://www.gsmarena.com/htc_one_mini_2-6345.php");
		urls.add("http://www.gsmarena.com/htc_desire_610-6160.php");
		urls.add("http://www.gsmarena.com/htc_one_max-5704.php");
		urls.add("http://www.gsmarena.com/htc_desire_310-6009.php");
		urls.add("http://www.gsmarena.com/htc_desire_820q_dual_sim-6854.php");
		urls.add("http://www.gsmarena.com/htc_butterfly-5118.php");
		urls.add("http://www.gsmarena.com/htc_desire_500-5623.php");
		urls.add("http://www.gsmarena.com/htc_desire_x-4951.php");
		urls.add("http://www.gsmarena.com/htc_desire_700_dual_sim-5870.php");
		urls.add("http://www.gsmarena.com/htc_droid_dna-5113.php");
		urls.add("http://www.gsmarena.com/htc_butterfly_s-5537.php");
		urls.add("http://www.gsmarena.com/htc_windows_phone_8x-4975.php");
		urls.add("http://www.gsmarena.com/htc_one_v-4575.php");
		urls.add("http://www.gsmarena.com/htc_droid_incredible_4g_lte-4744.php");
		urls.add("http://www.gsmarena.com/htc_vivid-4302.php");
		urls.add("http://www.gsmarena.com/htc_desire_612-6719.php");
		urls.add("http://www.gsmarena.com/htc_desire_310_dual_sim-6348.php");
		urls.add("http://www.gsmarena.com/htc_one_remix-6528.php");
		urls.add("http://www.gsmarena.com/htc_sensation-3875.php");
		urls.add("http://www.gsmarena.com/htc_one_sv-5105.php");
		urls.add("http://www.gsmarena.com/htc_desire_hd-3468.php");
		urls.add("http://www.gsmarena.com/htc_rezound-4099.php");
		urls.add("http://www.gsmarena.com/htc_radar-4131.php");
		urls.add("http://www.gsmarena.com/htc_wildfire_s-3777.php");
		urls.add("http://www.gsmarena.com/htc_rhyme-4132.php");
		urls.add("http://www.gsmarena.com/htc_desire_c-4759.php");
		urls.add("http://www.gsmarena.com/htc_desire_501_dual_sim-5907.php");
		urls.add("http://www.gsmarena.com/htc_explorer-4102.php");
		urls.add("http://www.gsmarena.com/htc_sensation_xe-4164.php");
		urls.add("http://www.gsmarena.com/htc_desire_700-6552.php");
		urls.add("http://www.gsmarena.com/htc_titan_ii-4411.php");
		urls.add("http://www.gsmarena.com/htc_incredible_s-3788.php");
		urls.add("http://www.gsmarena.com/htc_one_s_c2-4836.php");
		urls.add("http://www.gsmarena.com/htc_evo_4g-3427.php");
		
		urls.add("http://www.gsmarena.com/motorola_moto_e_%282015%29-6986.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g_4g_%282nd_gen%29-7137.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g_4g_dual_sim_%282nd_gen%29-6991.php");
		urls.add("http://www.gsmarena.com/motorola_moto_maxx-6779.php");
		urls.add("http://www.gsmarena.com/motorola_droid_turbo-6727.php");
		urls.add("http://www.gsmarena.com/motorola_nexus_6-6604.php");
		urls.add("http://www.gsmarena.com/motorola_moto_x_%282014%29-6649.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g_dual_sim_%282nd_gen%29-6648.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g_%282nd_gen%29-6647.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g_4g-6355.php");
		urls.add("http://www.gsmarena.com/motorola_luge-6806.php");
		urls.add("http://www.gsmarena.com/motorola_moto_e-6376.php");
		urls.add("http://www.gsmarena.com/motorola_moto_e_dual_sim-6323.php");
		urls.add("http://www.gsmarena.com/motorola_moto_g-5831.php");
		urls.add("http://www.gsmarena.com/motorola_moto_x-5601.php");
		urls.add("http://www.gsmarena.com/motorola_droid_ultra-5605.php");
		urls.add("http://www.gsmarena.com/motorola_droid_maxx-5604.php");
		urls.add("http://www.gsmarena.com/motorola_droid_mini-5603.php");
		urls.add("http://www.gsmarena.com/motorola_razr_d3_xt919-5356.php");
		urls.add("http://www.gsmarena.com/motorola_razr_d1-5355.php");
		urls.add("http://www.gsmarena.com/motorola_electrify_m_xt905-5102.php");
		urls.add("http://www.gsmarena.com/motorola_razr_i_xt890-4998.php");
		urls.add("http://www.gsmarena.com/motorola_droid_razr_maxx_hd-4972.php");
		urls.add("http://www.gsmarena.com/motorola_droid_razr_hd-4971.php");
		urls.add("http://www.gsmarena.com/motorola_razr_hd_xt925-4970.php");
		urls.add("http://www.gsmarena.com/motorola_droid_razr_m-4973.php");
		urls.add("http://www.gsmarena.com/motorola_razr_m_xt905-4974.php");
		urls.add("http://www.gsmarena.com/motorola_defy_xt_xt556-4892.php");
		urls.add("http://www.gsmarena.com/motorola_electrify_2_xt881-4891.php");
		urls.add("http://www.gsmarena.com/motorola_photon_q_4g_lte_xt897-4885.php");
		urls.add("http://www.gsmarena.com/motorola_defy_pro_xt560-4868.php");
		urls.add("http://www.gsmarena.com/motorola_atrix_hd_mb886-4867.php");
		urls.add("http://www.gsmarena.com/motorola_xt760-4820.php");
		urls.add("http://www.gsmarena.com/motorola_atrix_tv_xt687-4921.php");
		urls.add("http://www.gsmarena.com/motorola_atrix_tv_xt682-4797.php");
		urls.add("http://www.gsmarena.com/motorola_motosmart_me_xt303-5153.php");
		urls.add("http://www.gsmarena.com/motorola_razr_v_xt885-5224.php");
		urls.add("http://www.gsmarena.com/motorola_razr_v_xt889-4856.php");
		urls.add("http://www.gsmarena.com/motorola_razr_v_mt887-4778.php");
		urls.add("http://www.gsmarena.com/motorola_motosmart_mix_xt550-4762.php");
		urls.add("http://www.gsmarena.com/motorola_xt390-4696.php");
		urls.add("http://www.gsmarena.com/motorola_razr_maxx-4666.php");
		urls.add("http://www.gsmarena.com/motorola_defy_xt535-4622.php");
		urls.add("http://www.gsmarena.com/motorola_droid_4_xt894-4418.php");
		urls.add("http://www.gsmarena.com/motorola_droid_razr_maxx-4417.php");
		urls.add("http://www.gsmarena.com/motorola_motoluxe_mt680-4849.php");
		urls.add("http://www.gsmarena.com/motorola_motoluxe_xt389-4848.php");
		urls.add("http://www.gsmarena.com/motorola_motoluxe-4404.php");
		urls.add("http://www.gsmarena.com/motorola_defy_mini_xt321-4847.php");
		urls.add("http://www.gsmarena.com/motorola_defy_mini_xt320-4375.php");
		urls.add("http://www.gsmarena.com/motorola_xt319-4918.php");
		urls.add("http://www.gsmarena.com/motorola_fire-4386.php");
		urls.add("http://www.gsmarena.com/motorola_mt917-4383.php");
		urls.add("http://www.gsmarena.com/motorola_xt928-4382.php");
		urls.add("http://www.gsmarena.com/motorola_xt532-4355.php");
		urls.add("http://www.gsmarena.com/motorola_moto_xt615-4348.php");
		urls.add("http://www.gsmarena.com/motorola_razr_xt910-4273.php");
		urls.add("http://www.gsmarena.com/motorola_droid_razr_xt912-4101.php");
		urls.add("http://www.gsmarena.com/motorola_atrix_2_mb865-4199.php");
		urls.add("http://www.gsmarena.com/motorola_admiral_xt603-4282.php");
		urls.add("http://www.gsmarena.com/motorola_me632-4272.php");
		urls.add("http://www.gsmarena.com/motorola_pro+-4128.php");
		urls.add("http://www.gsmarena.com/motorola_defy+-4098.php");
		urls.add("http://www.gsmarena.com/motorola_fire_xt-4160.php");
		urls.add("http://www.gsmarena.com/motorola_fire_xt311-4045.php");
		urls.add("http://www.gsmarena.com/motorola_spice_key_xt317-4209.php");
		urls.add("http://www.gsmarena.com/motorola_spice_key-4046.php");
		urls.add("http://www.gsmarena.com/motorola_milestone_3_xt860-4349.php");
		urls.add("http://www.gsmarena.com/motorola_droid_3-4036.php");
		urls.add("http://www.gsmarena.com/motorola_triumph-3988.php");
		urls.add("http://www.gsmarena.com/motorola_photon_4g_mb855-3987.php");
		urls.add("http://www.gsmarena.com/motorola_moto_mt870-4023.php");
		urls.add("http://www.gsmarena.com/motorola_moto_mt620-3982.php");
		urls.add("http://www.gsmarena.com/motorola_milestone_xt883-4025.php");
		urls.add("http://www.gsmarena.com/motorola_moto_xt882-3981.php");
		urls.add("http://www.gsmarena.com/motorola_moto_xt316-4024.php");
		urls.add("http://www.gsmarena.com/motorola_xprt_mb612-3946.php");
		urls.add("http://www.gsmarena.com/motorola_pro-3781.php");
		urls.add("http://www.gsmarena.com/motorola_atrix-3709.php");
		urls.add("http://www.gsmarena.com/motorola_atrix_4g-3708.php");
		urls.add("http://www.gsmarena.com/motorola_cliq_2-3454.php");
		urls.add("http://www.gsmarena.com/motorola_droid_bionic_xt875-3710.php");
		urls.add("http://www.gsmarena.com/motorola_droid_x_me811-3730.php");
		urls.add("http://www.gsmarena.com/motorola_droid_bionic_xt865-4523.php");
		urls.add("http://www.gsmarena.com/motorola_moto_me525-3912.php");
		urls.add("http://www.gsmarena.com/motorola_milestone_2_me722-3911.php");
		urls.add("http://www.gsmarena.com/motorola_droid_2_global-3636.php");
		urls.add("http://www.gsmarena.com/motorola_droid_pro_xt610-3541.php");
		urls.add("http://www.gsmarena.com/motorola_xt301-3628.php");
		urls.add("http://www.gsmarena.com/motorola_spice_xt300-3540.php");
		urls.add("http://www.gsmarena.com/motorola_flipside_mb508-3539.php");
		urls.add("http://www.gsmarena.com/motorola_moto_mt716-3535.php");
		urls.add("http://www.gsmarena.com/motorola_bravo_mb520-3538.php");
		urls.add("http://www.gsmarena.com/motorola_citrus_wx445-3542.php");
		urls.add("http://www.gsmarena.com/motorola_defy-3514.php");
		urls.add("http://www.gsmarena.com/motorola_milestone_2-3495.php");
		urls.add("http://www.gsmarena.com/motorola_droid_2-3475.php");
		urls.add("http://www.gsmarena.com/motorola_mt810lx-3626.php");
		urls.add("http://www.gsmarena.com/motorola_xt810-3521.php");
		urls.add("http://www.gsmarena.com/motorola_xt806-3476.php");
		
		urls.add("http://www.gsmarena.com/alcatel_flash-7189.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_3_%285_5%29-7081.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_3_%284_7%29-7080.php");
		urls.add("http://www.gsmarena.com/alcatel_orange_klif-7092.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%285_5%29_lte-7093.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%285_5%29-7094.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%288%29_3g-7098.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%284%29-6933.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%284_5%29-6934.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%285%29-6935.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_10-6936.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%287%29-7095.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%287%29_3g-7096.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%287%29_lte-7097.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%283_5%29_firefox-6979.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_3_%283_5%29-6932.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_d3-6774.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_d1-6773.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_2_%285%29-6700.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_2_%285%29_premium-7123.php");
		urls.add("http://www.gsmarena.com/alcatel_fire_c_2g-6712.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_icon-6732.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_2_%284%29-6699.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_2_%284_5%29_dual_sim-6657.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_2_%284_5%29-6656.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_fierce_2-7154.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_evolve_2-7153.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_8s-6655.php");
		urls.add("http://www.gsmarena.com/alcatel_hero_8-6654.php");
		urls.add("http://www.gsmarena.com/alcatel_2010-6695.php");
		urls.add("http://www.gsmarena.com/alcatel_2012-6931.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_8-6459.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c2-6516.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_d5-6599.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_pixi_2-6619.php");
		urls.add("http://www.gsmarena.com/alcatel_hero_2-6653.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_7s-6165.php");
		urls.add("http://www.gsmarena.com/alcatel_pixi_7-6164.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_s9-6153.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_s7-6152.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_2-6130.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_2_s-6134.php");
		urls.add("http://www.gsmarena.com/alcatel_fire_c-6138.php");
		urls.add("http://www.gsmarena.com/alcatel_fire_e-6139.php");
		urls.add("http://www.gsmarena.com/alcatel_fire_s-6140.php");
		urls.add("http://www.gsmarena.com/alcatel_fire_7-6141.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_s3-6151.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_2_mini_s-6135.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_2_mini-6131.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_fit-6132.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_8-5947.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c9-5938.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_x+-5937.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c1-5691.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c3-5687.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c5-5692.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_c7-5693.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_evolve-5740.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_fierce-5741.php");
		urls.add("http://www.gsmarena.com/alcatel_pop_7-5939.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_alpha-5671.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_evo_8hd-5680.php");
		urls.add("http://www.gsmarena.com/alcatel_hero-5672.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_s-5668.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_mini-5669.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_t10-5449.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_snap_lte-5335.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_pixi-5681.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_snap-5334.php");
		urls.add("http://www.gsmarena.com/alcatel_idol_x-5318.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_fire-5319.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_star-5296.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_scribe_easy-5332.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_evo_7-5236.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_t_pop-5229.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_idol-5230.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_idol_ultra-5231.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_tab_7_hd-5232.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_tab_7-5233.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_tab_8_hd-5234.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_evo_7_hd-5235.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_s_pop-5228.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_m_pop-5242.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_x_pop-5227.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_scribe_hd_lte-5226.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_983-5139.php");
		urls.add("http://www.gsmarena.com/alcatel_view-5159.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_scribe_hd-5218.php");
		urls.add("http://www.gsmarena.com/alcatel_one_touch_scribe_x-5225.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_978-5103.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_988_shockwave-5080.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_993-4846.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_903-4845.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_992d-5866.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_997-5165.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_997d-5110.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_838-4844.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_668-4843.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_605-4842.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_986-4780.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_991-4733.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_916-4732.php");
		urls.add("http://www.gsmarena.com/alcatel_ot_720-4731.php");
		urls.add("http://www.gsmarena.com/blackberry_leap-7099.php");
		urls.add("http://www.gsmarena.com/blackberry_classic_non_camera-7066.php");
		urls.add("http://www.gsmarena.com/blackberry_porsche_design_p_9983-6691.php");
		urls.add("http://www.gsmarena.com/blackberry_passport-6457.php");
		urls.add("http://www.gsmarena.com/blackberry_classic-6458.php");
		urls.add("http://www.gsmarena.com/blackberry_z3-6163.php");
		urls.add("http://www.gsmarena.com/blackberry_porsche_design_p_9982-5856.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9320-4458.php");
		urls.add("http://www.gsmarena.com/blackberry_4g_lte_playbook-3846.php");
		urls.add("http://www.gsmarena.com/blackberry_q10-5274.php");
		urls.add("http://www.gsmarena.com/blackberry_z10-5251.php");
		urls.add("http://www.gsmarena.com/blackberry_q5-5452.php");
		urls.add("http://www.gsmarena.com/blackberry_9720-5625.php");
		urls.add("http://www.gsmarena.com/blackberry_z30-5711.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9220-4459.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9380-4331.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_9790-4332.php");
		urls.add("http://www.gsmarena.com/blackberry_porsche_design_p_9981-4288.php");
		urls.add("http://www.gsmarena.com/blackberry_torch_9810-3723.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9350-3756.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9360-3722.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_9370-4112.php");
		urls.add("http://www.gsmarena.com/blackberry_torch_9860-3926.php");
		urls.add("http://www.gsmarena.com/blackberry_torch_9850-4088.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_touch_9900-3116.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_touch_9930-3755.php");
		urls.add("http://www.gsmarena.com/blackberry_4g_playbook_hspa+-3900.php");
		urls.add("http://www.gsmarena.com/blackberry_playbook_wimax-3899.php");
		urls.add("http://www.gsmarena.com/blackberry_playbook-3830.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_3g_9100-3032.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_3g_9105-3287.php");
		urls.add("http://www.gsmarena.com/blackberry_torch_9800-3203.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_3g_9300-3422.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_3g_9330-3591.php");
		urls.add("http://www.gsmarena.com/blackberry_style_9670-3326.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_9780-3431.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_9650-3284.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_9700-2963.php");
		urls.add("http://www.gsmarena.com/blackberry_storm2_9520-2962.php");
		urls.add("http://www.gsmarena.com/blackberry_storm2_9550-2970.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8530-3592.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8520-2889.php");
		urls.add("http://www.gsmarena.com/blackberry_tour_9630-2868.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_flip_8220-2521.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_flip_8230-3593.php");
		urls.add("http://www.gsmarena.com/blackberry_storm_9530-2540.php");
		urls.add("http://www.gsmarena.com/blackberry_storm_9500-2534.php");
		urls.add("http://www.gsmarena.com/blackberry_storm3-3529.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8900-2604.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8980-3675.php");
		urls.add("http://www.gsmarena.com/blackberry_bold_9000-2370.php");
		urls.add("http://www.gsmarena.com/blackberry_volt-3754.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_8130-3933.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_8110-2226.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8310-2050.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8320-2121.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8330-3594.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_8120-2136.php");
		urls.add("http://www.gsmarena.com/blackberry_8800-1911.php");
		urls.add("http://www.gsmarena.com/blackberry_8830_world_edition-1968.php");
		urls.add("http://www.gsmarena.com/blackberry_8820-2033.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_8300-1979.php");
		urls.add("http://www.gsmarena.com/blackberry_pearl_8100-1701.php");
		urls.add("http://www.gsmarena.com/blackberry_7130g-1622.php");
		urls.add("http://www.gsmarena.com/blackberry_7130c-1623.php");
		urls.add("http://www.gsmarena.com/blackberry_7290-1348.php");
		urls.add("http://www.gsmarena.com/blackberry_7100v-1012.php");
		urls.add("http://www.gsmarena.com/blackberry_7100t-1011.php");
		urls.add("http://www.gsmarena.com/blackberry_7100x-1013.php");
		urls.add("http://www.gsmarena.com/blackberry_8700c-1349.php");
		urls.add("http://www.gsmarena.com/blackberry_8707v-1575.php");
		urls.add("http://www.gsmarena.com/blackberry_7130v-1621.php");
		urls.add("http://www.gsmarena.com/blackberry_7730-1010.php");
		urls.add("http://www.gsmarena.com/blackberry_7230-1009.php");
		urls.add("http://www.gsmarena.com/blackberry_6720-1008.php");
		urls.add("http://www.gsmarena.com/blackberry_6230-1007.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_touch-3934.php");
		urls.add("http://www.gsmarena.com/blackberry_curve_touch_cdma-3757.php");
		urls.add("http://www.gsmarena.com/blackberry_playbook_2012-4460.php");
		urls.add("http://www.gsmarena.com/blackberry_porsche_design_p_9531-4463.php");
		urls.add("http://www.gsmarena.com/lenovo_k80-7216.php");
		urls.add("http://www.gsmarena.com/lenovo_s60-7214.php");
		urls.add("http://www.gsmarena.com/lenovo_a6000_plus-7197.php");
		urls.add("http://www.gsmarena.com/lenovo_a1900-7192.php");
		urls.add("http://www.gsmarena.com/lenovo_k3_note-7147.php");
		urls.add("http://www.gsmarena.com/lenovo_vibe_shot-7046.php");
		urls.add("http://www.gsmarena.com/lenovo_a7000-7088.php");
		urls.add("http://www.gsmarena.com/lenovo_tab_2_a7_10-6955.php");
		urls.add("http://www.gsmarena.com/lenovo_tab_2_a7_30-6956.php");
		urls.add("http://www.gsmarena.com/lenovo_p70-7063.php");
		urls.add("http://www.gsmarena.com/lenovo_ideapad_miix_300-7091.php");
		urls.add("http://www.gsmarena.com/lenovo_tab_2_a8-7090.php");
		urls.add("http://www.gsmarena.com/lenovo_tab_2_a10_70-7089.php");
		urls.add("http://www.gsmarena.com/lenovo_a5000-7167.php");
		urls.add("http://www.gsmarena.com/lenovo_a6000-6938.php");
		urls.add("http://www.gsmarena.com/lenovo_p90-6920.php");
		urls.add("http://www.gsmarena.com/lenovo_vibe_x2_pro-6919.php");
		urls.add("http://www.gsmarena.com/lenovo_k3-6848.php");
		urls.add("http://www.gsmarena.com/lenovo_a319-6789.php");
		urls.add("http://www.gsmarena.com/lenovo_s856-6788.php");
		urls.add("http://www.gsmarena.com/lenovo_a916-6855.php");
		urls.add("http://www.gsmarena.com/lenovo_golden_warrior_note_8-6842.php");
		urls.add("http://www.gsmarena.com/lenovo_s90_sisley-6739.php");
		urls.add("http://www.gsmarena.com/lenovo_s580-6787.php");
		urls.add("http://www.gsmarena.com/lenovo_a606-6746.php");
		urls.add("http://www.gsmarena.com/lenovo_yoga_tablet_2_pro-6852.php");
		urls.add("http://www.gsmarena.com/lenovo_yoga_tablet_2_10_1-6731.php");
		urls.add("http://www.gsmarena.com/lenovo_yoga_tablet_2_8_0_-6730.php");
		urls.add("http://www.gsmarena.com/lenovo_tab_s8-6681.php");
		urls.add("http://www.gsmarena.com/lenovo_s939-6370.php");
		urls.add("http://www.gsmarena.com/lenovo_golden_warrior_s8-6293.php");
		urls.add("http://www.gsmarena.com/lenovo_golden_warrior_a8-6529.php");
		urls.add("http://www.gsmarena.com/lenovo_vibe_z2_pro-6396.php");
		urls.add("http://www.gsmarena.com/lenovo_a850+-6595.php");
		urls.add("http://www.gsmarena.com/lenovo_vibe_z2-6642.php");
		urls.add("http://www.gsmarena.com/lenovo_vibe_x2-6643.php");
		urls.add("http://www.gsmarena.com/huawei_y625-7206.php");
		urls.add("http://www.gsmarena.com/huawei_honor_4c-7203.php");
		urls.add("http://www.gsmarena.com/huawei_p8max-7200.php");
		urls.add("http://www.gsmarena.com/huawei_p8_lite-7201.php");
		urls.add("http://www.gsmarena.com/huawei_p8-7006.php");
		urls.add("http://www.gsmarena.com/huawei_snapto-7187.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_x2-7075.php");
		urls.add("http://www.gsmarena.com/huawei_honor_6_plus-6777.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_gx1-6896.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y221-6908.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y520-6909.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y540-7049.php");
		urls.add("http://www.gsmarena.com/huawei_y360-7077.php");
		urls.add("http://www.gsmarena.com/huawei_y635-7076.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_mate7_monarch-6869.php");
		urls.add("http://www.gsmarena.com/huawei_honor_4x-6754.php");
		urls.add("http://www.gsmarena.com/huawei_honor_holly-6738.php");
		urls.add("http://www.gsmarena.com/huawei_honor_tablet-6705.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g7-6646.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y550-6676.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g620s-6677.php");
		urls.add("http://www.gsmarena.com/huawei_honor_4_play-6692.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g535-6678.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3c_4g-6395.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3x_pro-6398.php");
		urls.add("http://www.gsmarena.com/huawei_honor_6-6461.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3c_play-6603.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_mate7-6543.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p7_sapphire_edition-6611.php");
		urls.add("http://www.gsmarena.com/huawei_y300ii-6596.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g630-6499.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y330-6493.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_plus-6375.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p7-6124.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p7_mini-6332.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g730-6290.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y600-6278.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_10_link+-6169.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g6_4g-6168.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g6-6136.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_m1-6137.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_x1-6129.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y530-6103.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3c-5903.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3x_g750-5902.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y220-5921.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y320-5936.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_mate2_4g-5949.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p6_s-5979.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_7_youth2-5981.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g740-5840.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y511-5910.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_w2-5485.php");
		urls.add("http://www.gsmarena.com/huawei_g6153-5739.php");
		urls.add("http://www.gsmarena.com/huawei_g610s-5699.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g700-5633.php");
		urls.add("http://www.gsmarena.com/huawei_honor_3-5664.php");
		urls.add("http://www.gsmarena.com/huawei_g3621l-5779.php");
		urls.add("http://www.gsmarena.com/huawei_premia_4g_m931-5382.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y300-5386.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p6-5467.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_7_vogue-5539.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_7_youth-5698.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g525-5632.php");
		urls.add("http://www.gsmarena.com/huawei_u8687_cronos-6893.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y210d-5365.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p2-5267.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g615-5257.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g526-5327.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g350-5648.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g350-5648.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_w1-5065.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_mate-5237.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_d2-5164.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g510-5250.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g500-5141.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y201_pro-5112.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_10_link-5507.php");
		urls.add("http://www.gsmarena.com/huawei_honor_2-5092.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_7_lite-4882.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g330-4966.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g600-4963.php");
		urls.add("http://www.gsmarena.com/huawei_fusion_2_u8665-5020.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p1_lte-5022.php");
		urls.add("http://www.gsmarena.com/huawei_summit-5068.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y-5077.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y100-4839.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_y200-4838.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g330d_u8825d-5383.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_g300-4594.php");
		urls.add("http://www.gsmarena.com/huawei_g6005-5848.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_q_m5660-4737.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p1-4410.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p1_xl_u9200e-5003.php");
		urls.add("http://www.gsmarena.com/huawei_fusion_u8652-4656.php");
		urls.add("http://www.gsmarena.com/huawei_g6609-4698.php");
		urls.add("http://www.gsmarena.com/huawei_g5520-5108.php");
		urls.add("http://www.gsmarena.com/huawei_activa_4g-4837.php");
		urls.add("http://www.gsmarena.com/huawei_g5000-4840.php");
		urls.add("http://www.gsmarena.com/huawei_g6310-4841.php");
		urls.add("http://www.gsmarena.com/huawei_g6800-5109.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad_10_fhd-4587.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_d1_xl_u9500e-5002.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_d1-4570.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_d_quad_xl-4569.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_d_quad-4568.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_p1s-4409.php");
		urls.add("http://www.gsmarena.com/huawei_m886_mercury-4381.php");
		urls.add("http://www.gsmarena.com/huawei_g7300-4335.php");
		urls.add("http://www.gsmarena.com/huawei_g7005-4334.php");
		urls.add("http://www.gsmarena.com/huawei_mediapad-4264.php");
		urls.add("http://www.gsmarena.com/huawei_u8520_duplex-4260.php");
		urls.add("http://www.gsmarena.com/huawei_t8300-4636.php");
		urls.add("http://www.gsmarena.com/huawei_ascend_ii-4057.php");
		urls.add("http://www.gsmarena.com/huawei_u8850_vision-4109.php");
		urls.add("http://www.gsmarena.com/huawei_u8860_honor-4197.php");
		urls.add("http://www.gsmarena.com/huawei_impulse_4g-4142.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_10_a3_a30-7218.php");
		urls.add("http://www.gsmarena.com/acer_iconia_one_8_b1_820-7217.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a3_a20-7136.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a3_a20fhd-7135.php");
		urls.add("http://www.gsmarena.com/acer_liquid_jade_z-7072.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z520-7073.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z220-7074.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e700-6420.php");
		urls.add("http://www.gsmarena.com/acer_liquid_jade-6423.php");
		urls.add("http://www.gsmarena.com/acer_liquid_x1-6419.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z500-6635.php");
		urls.add("http://www.gsmarena.com/acer_liquid_jade_s-6864.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z410-6912.php");
		urls.add("http://www.gsmarena.com/acer_liquid_m220-7071.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e600-6421.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z200-6422.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_8_a1_840fhd-6424.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_7_a1_713hd-6342.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e3-6116.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e3_duo_plus-6680.php");
		urls.add("http://www.gsmarena.com/acer_iconia_one_7_b1_730-6341.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_7_a1_713-6343.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z3-5624.php");
		urls.add("http://www.gsmarena.com/acer_liquid_s2-5670.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z5-5929.php");
		urls.add("http://www.gsmarena.com/acer_iconia_a1_830-5930.php");
		urls.add("http://www.gsmarena.com/acer_iconia_b1_720-5932.php");
		urls.add("http://www.gsmarena.com/acer_iconia_b1_721-5933.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z4-6115.php");
		urls.add("http://www.gsmarena.com/acer_liquid_s1-5496.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a3-5700.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a1_811-5892.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a1_810-5399.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e2-5418.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z2-5302.php");
		urls.add("http://www.gsmarena.com/acer_liquid_c1-5276.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e1-5262.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_b1_710-5897.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_b1_a71-5239.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a110-5067.php");
		urls.add("http://www.gsmarena.com/acer_liquid_z110-5057.php");
		urls.add("http://www.gsmarena.com/acer_liquid_gallant_e350-4924.php");
		urls.add("http://www.gsmarena.com/acer_liquid_gallant_duo-4871.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a511-4643.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a700-4425.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a701-4934.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a200-4450.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a210-5066.php");
		urls.add("http://www.gsmarena.com/acer_cloudmobile_s500-4542.php");
		urls.add("http://www.gsmarena.com/acer_liquid_glow_e330-4589.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a510-4642.php");
		urls.add("http://www.gsmarena.com/acer_allegro-3966.php");
		urls.add("http://www.gsmarena.com/acer_liquid_express_e320-4261.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a501-3898.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a100-3841.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a101-3906.php");
		urls.add("http://www.gsmarena.com/acer_iconia_tab_a500-3907.php");
		urls.add("http://www.gsmarena.com/acer_iconia_smart-3662.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e120-3406.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e130-3373.php");
		urls.add("http://www.gsmarena.com/acer_betouch_t500-3587.php");
		urls.add("http://www.gsmarena.com/acer_liquid_mt-3519.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e140-3666.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e210-3712.php");
		urls.add("http://www.gsmarena.com/acer_liquid_mini_e310-3711.php");
		urls.add("http://www.gsmarena.com/acer_stream-3358.php");
		urls.add("http://www.gsmarena.com/acer_liquid_e-3156.php");
		urls.add("http://www.gsmarena.com/acer_neotouch_p400-3155.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e400-3154.php");
		urls.add("http://www.gsmarena.com/acer_neotouch_p300-3138.php");
		urls.add("http://www.gsmarena.com/acer_betouch_e110-3137.php");
		urls.add("http://www.gsmarena.com/acer_liquid-2968.php");
		urls.add("http://www.gsmarena.com/acer_neotouch-2958.php");
		urls.add("http://www.gsmarena.com/zte_blade_s6_plus-7168.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z9_max-7116.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z9_mini-7149.php");
		urls.add("http://www.gsmarena.com/zte_open_l-7106.php");
		urls.add("http://www.gsmarena.com/zte_grand_s3-7078.php");
		urls.add("http://www.gsmarena.com/zte_blade_l3-7105.php");
		urls.add("http://www.gsmarena.com/zte_blade_g_lux-7057.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_plus_z826-6904.php");
		urls.add("http://www.gsmarena.com/zte_star_2-6914.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_max+-6915.php");
		urls.add("http://www.gsmarena.com/zte_imperial_ii-7157.php");
		urls.add("http://www.gsmarena.com/zte_blade_s6-6954.php");
		urls.add("http://www.gsmarena.com/zte_v5_lux-7056.php");
		urls.add("http://www.gsmarena.com/zte_blade_g-7058.php");
		urls.add("http://www.gsmarena.com/zte_speed-6898.php");
		urls.add("http://www.gsmarena.com/zte_grand_s_ii-6847.php");
		urls.add("http://www.gsmarena.com/zte_grand_s_pro-7155.php");
		urls.add("http://www.gsmarena.com/zte_zinger-7156.php");
		urls.add("http://www.gsmarena.com/zte_blade_vec_3g-6644.php");
		urls.add("http://www.gsmarena.com/zte_blade_vec_3g-6644.php");
		urls.add("http://www.gsmarena.com/zte_zmax-6697.php");
		urls.add("http://www.gsmarena.com/zte_grand_xmax-6718.php");
		urls.add("http://www.gsmarena.com/zte_kis_3-6579.php");
		urls.add("http://www.gsmarena.com/zte_kis_3-6579.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z7_mini-6492.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z7_max-6491.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z7-6490.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z5s_mini_nx405h-6607.php");
		urls.add("http://www.gsmarena.com/zte_kis_3_max-6641.php");
		urls.add("http://www.gsmarena.com/zte_blade_g2-6381.php");
		urls.add("http://www.gsmarena.com/zte_star_1-6324.php");
		urls.add("http://www.gsmarena.com/zte_redbull_v5_v9180-6679.php");
		urls.add("http://www.gsmarena.com/zte_nubia_x6-6236.php");
		urls.add("http://www.gsmarena.com/zte_grand_memo_ii_lte-6154.php");
		urls.add("http://www.gsmarena.com/zte_open_c-6155.php");
		urls.add("http://www.gsmarena.com/zte_open_ii-6156.php");
		urls.add("http://www.gsmarena.com/zte_iconic_phablet-5962.php");
		urls.add("http://www.gsmarena.com/zte_sonata_4g-5963.php");
		urls.add("http://www.gsmarena.com/zte_grand_s_ii_s291-5948.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z5s-5852.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z5s_mini_nx403a-5853.php");
		urls.add("http://www.gsmarena.com/zte_grand_s_flex-5834.php");
		urls.add("http://www.gsmarena.com/zte_blade_q_maxi-5826.php");
		urls.add("http://www.gsmarena.com/zte_imperial-5552.php");
		urls.add("http://www.gsmarena.com/zte_reef-5659.php");
		urls.add("http://www.gsmarena.com/zte_blade_g_v880g-5620.php");
		urls.add("http://www.gsmarena.com/zte_blade_v-5682.php");
		urls.add("http://www.gsmarena.com/zte_warp_4g-5755.php");
		urls.add("http://www.gsmarena.com/zte_blade_q_mini-5824.php");
		urls.add("http://www.gsmarena.com/zte_blade_q-5825.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_quad_v987-5376.php");
		urls.add("http://www.gsmarena.com/zte_grand_x2_in-5455.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_pro-5499.php");
		urls.add("http://www.gsmarena.com/zte_vital_n9810-5511.php");
		urls.add("http://www.gsmarena.com/zte_blade_iii_pro-5425.php");
		urls.add("http://www.gsmarena.com/zte_geek_v975-5402.php");
		urls.add("http://www.gsmarena.com/zte_grand_memo_v9815-5330.php");
		urls.add("http://www.gsmarena.com/zte_open-5320.php");
		urls.add("http://www.gsmarena.com/zte_v887-5135.php");
		urls.add("http://www.gsmarena.com/zte_v889m-5136.php");
		urls.add("http://www.gsmarena.com/zte_avid_4g-5173.php");
		urls.add("http://www.gsmarena.com/zte_grand_s-5240.php");
		urls.add("http://www.gsmarena.com/zte_v81-5269.php");
		urls.add("http://www.gsmarena.com/zte_director-5470.php");
		urls.add("http://www.gsmarena.com/zte_blade_c_v807-5277.php");
		urls.add("http://www.gsmarena.com/zte_kis_iii_v790-5134.php");
		urls.add("http://www.gsmarena.com/zte_groove_x501-5133.php");
		urls.add("http://www.gsmarena.com/zte_nubia_z5-5647.php");
		urls.add("http://www.gsmarena.com/zte_flash-4893.php");
		urls.add("http://www.gsmarena.com/zte_anthem_4g-5006.php");
		urls.add("http://www.gsmarena.com/zte_warp_sequent-5007.php");
		urls.add("http://www.gsmarena.com/zte_grand_era_u895-5004.php");
		urls.add("http://www.gsmarena.com/zte_blade_iii-4983.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_in-4962.php");
		urls.add("http://www.gsmarena.com/zte_n880e-4880.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_lte_t82-4873.php");
		urls.add("http://www.gsmarena.com/zte_grand_x_v970-4597.php");
		urls.add("http://www.gsmarena.com/zte_u880e-4776.php");
		urls.add("http://www.gsmarena.com/zte_score_m-4650.php");
		urls.add("http://www.gsmarena.com/zte_pf112_hd-4582.php");
		urls.add("http://www.gsmarena.com/zte_era-4581.php");
		urls.add("http://www.gsmarena.com/zte_light_tab_3_v9s-4592.php");
		urls.add("http://www.gsmarena.com/zte_t98-4591.php");
		urls.add("http://www.gsmarena.com/zte_pf_100-4590.php");
		urls.add("http://www.gsmarena.com/zte_v96-4593.php");
		urls.add("http://www.gsmarena.com/zte_skate_acqua-4583.php");
		urls.add("http://www.gsmarena.com/zte_orbit-4585.php");
		urls.add("http://www.gsmarena.com/zte_kis_v788-4586.php");
		urls.add("http://www.gsmarena.com/zte_v880e-4598.php");
		urls.add("http://www.gsmarena.com/zte_light_tab_2_v9a-4467.php");
		urls.add("http://www.gsmarena.com/zte_optik-4506.php");
		urls.add("http://www.gsmarena.com/zte_pf200-4556.php");
		urls.add("http://www.gsmarena.com/zte_n910-4557.php");
		urls.add("http://www.gsmarena.com/zte_blade_ii_v880+-4608.php");
		urls.add("http://www.gsmarena.com/zte_v875-4607.php");
		urls.add("http://www.gsmarena.com/zte_tania-4304.php");
		urls.add("http://www.gsmarena.com/zte_warp-4313.php");
		urls.add("http://www.gsmarena.com/zte_score-4311.php");
		urls.add("http://www.gsmarena.com/zte_v9-3903.php");
		urls.add("http://www.gsmarena.com/zte_n721-4760.php");
		urls.add("http://www.gsmarena.com/zte_skate-3784.php");
		urls.add("http://www.gsmarena.com/zte_avail-4244.php");
		urls.add("http://www.gsmarena.com/zte_u900-3791.php");
		urls.add("http://www.gsmarena.com/zte_libra-3790.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_go-6466.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_7c_at7_b8-6467.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_pro-5500.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_write-5501.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_pure-5502.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_10_se-5154.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_13_at335-4691.php");
		urls.add("http://www.gsmarena.com/toshiba_thrive-3970.php");
		urls.add("http://www.gsmarena.com/toshiba_windows_phone_is12t-4076.php");
		urls.add("http://www.gsmarena.com/toshiba_thrive_7-4203.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_at200-4400.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_7_7_at275-4693.php");
		urls.add("http://www.gsmarena.com/toshiba_excite_10_at305-4692.php");
		urls.add("http://www.gsmarena.com/toshiba_tg02-3159.php");
		urls.add("http://www.gsmarena.com/toshiba_tg01-2662.php");
		urls.add("http://www.gsmarena.com/toshiba_g810-2273.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_2_ze500cl-7044.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_2_ze550ml-7120.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_2_ze551ml-6917.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7_fe375cl-7045.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_c_zc451cg-6982.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7_fe171cg-6953.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_zoom_zx550-6918.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_5_a500kl-6429.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_7_me572c-6629.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_7_me572cl-6630.php");
		urls.add("http://www.gsmarena.com/asus_padfone_x_mini-6737.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_10_me103k-6751.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_5_lite_a502cg-6813.php");
		urls.add("http://www.gsmarena.com/asus_pegasus-6897.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_4_a450cg-6428.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_8_me581cl-6414.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_8_me181c-6413.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_7_me176c-6412.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7_fe375cg-6410.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7_fe375cxg-6747.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_8_fe380cg-6411.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_6_a601cg-6853.php");
		urls.add("http://www.gsmarena.com/asus_padfone_e-5993.php");
		urls.add("http://www.gsmarena.com/asus_padfone_infinity_lite-6120.php");
		urls.add("http://www.gsmarena.com/asus_padfone_s-6238.php");
		urls.add("http://www.gsmarena.com/asus_padfone_x-6519.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7_%282014%29-6394.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_6-5953.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_5_a501cg-7160.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_5_a500cg-5952.php");
		urls.add("http://www.gsmarena.com/asus_zenfone_4-5951.php");
		urls.add("http://www.gsmarena.com/asus_padfone_mini_4g_%28intel%29-7158.php");
		urls.add("http://www.gsmarena.com/asus_padfone_mini_%28intel%29-5982.php");
		urls.add("http://www.gsmarena.com/asus_padfone_mini-5891.php");
		urls.add("http://www.gsmarena.com/asus_padfone_infinity_2-5706.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_10-5676.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_8_me180a-5675.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_7-5674.php");
		urls.add("http://www.gsmarena.com/asus_google_nexus_7_%282013%29-5600.php");
		urls.add("http://www.gsmarena.com/asus_fonepad_note_fhd6-5494.php");
		urls.add("http://www.gsmarena.com/asus_padfone_infinity-5328.php");
		urls.add("http://www.gsmarena.com/asus_fonepad-5329.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_hd7_16_gb-5492.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_hd7_8_gb-5879.php");
		urls.add("http://www.gsmarena.com/asus_memo_pad_me172v-5249.php");
		urls.add("http://www.gsmarena.com/asus_google_nexus_7_cellular-5091.php");
		urls.add("http://www.gsmarena.com/asus_padfone_2-5017.php");
		urls.add("http://www.gsmarena.com/asus_p835-2727.php");
		urls.add("http://www.gsmarena.com/asus_p550-2193.php");
		urls.add("http://www.gsmarena.com/asus_padfone-3965.php");
		urls.add("http://www.gsmarena.com/asus_memo-4422.php");
		urls.add("http://www.gsmarena.com/asus_e600-3696.php");
		
		
		return urls;
	}
}